[package]
name    = "render-cms"
version = "0.1.0"
edition = "2021"

[dependencies]
m6-render  = { path = "../../../../m6/m6-render" }
serde_json = "1"
comrak     = { version = "0.21", default-features = false }
base64     = "0.22"

[dev-dependencies]
rcgen         = "0.13"
rustls        = { version = "0.23", default-features = false, features = ["ring", "std"] }
rustls-pemfile = "2"
tempfile      = "3"
