[workspace]
members = [
    "examples/03-contact/render-contact",
    "examples/04-auth/render-contact",
    "examples/05-cms/render-cms",
    "examples/07-dev-to-production/render-cms",
]
resolver = "2"

# To build all renderers: cargo build --release
# To build one:           cargo build --release -p render-contact
#                         cargo build --release -p render-cms
