global_params = ["data/site.json"]

[[route]]
path     = "/"
template = "templates/home.html"
cache    = "public"

[[route]]
path     = "/logs"
template = "templates/logs.html"
cache    = "no-store"

[[route]]
path     = "/bench"
template = "templates/bench.html"
cache    = "no-store"
headers  = [
  ["Cross-Origin-Opener-Policy",   "same-origin"],
  ["Cross-Origin-Embedder-Policy", "require-corp"],
]
