global_params = ["data/site.json"]

[[route]]
path     = "/"
template = "templates/home.html"
params   = ["data/posts.json"]

[[route]]
path     = "/about"
template = "templates/page.html"
params   = ["data/about.json"]

[[route]]
path     = "/blog"
template = "templates/post-index.html"
params   = ["data/posts.json"]

[[route]]
path     = "/blog/{stem}"
template = "templates/post.html"
params   = ["data/posts.json"]

[[route]]
path     = "/login"
template = "templates/login.html"
params   = []
cache    = "no-store"

[[route]]
path     = "/_errors"
template = "templates/error.html"
params   = []
cache    = "no-store"
