global_params = ["data/site.json"]

[thread_pool]
size = 2

[[route]]
path  = "/contact"
cache = "no-store"

[[route]]
path  = "/cms"
cache = "no-store"

[[route]]
path  = "/cms/new"
cache = "no-store"

[[route]]
path  = "/cms/edit/{stem}"
cache = "no-store"

[[route]]
path  = "/api/drafts"
cache = "no-store"

[[route]]
path  = "/api/drafts/{stem}"
cache = "no-store"

[[route]]
path  = "/api/publish/{stem}"
cache = "no-store"

[[route]]
path  = "/api/unpublish/{stem}"
cache = "no-store"
